### ISSUE TITLE
Restructure project

### ISSUE THREAD

**Issue by leejy12** [ssook1222/madcamp_week1#1]
I think it'll be better if we move everything in `madcamp_week1` to the parent directory.

**Comment by ssook1222** [comment]
@leejy12 
I got it! 
The current project route is `mad camp 1/mad camp week 1`, so you want to change this part, right?
If I misunderstood, please reply! 😉

**Comment by leejy12** [comment]
That's correct! I have a commit ready now, asking for your approval to push 😁

**Comment by ssook1222** [comment]
Okay, let me know after you push!
